#!/bin/sh

# Make sure prerequisites are installed.
for app in trayer nm-applet; do
	if ! which "$app"; then
		echo "$app is not installed! xmobar may not work correctly!"
	fi
done

# Update fonts
if which fc-cache; then
	fc-cache -f
else
	echo 'fontconfig not found, cannot update font cache.'
fi

# Use fish.
if which fish && which wget; then
	chsh -s /usr/bin/fish

	# Install fundle.
	mkdir -p ~/.config/fish/functions
	wget https://git.io/fundle -O ~/.config/fish/functions/fundle.fish
else
	echo 'Fish or wget not found, not installing fish as default terminal.'
fi

# Install VS Code extensions
if which code; then
	for extension in EditorConfig.EditorConfig MaxfieldWalker.vscode-color-theme-spirited-away PeterJausovec.vscode-docker abusaidm.html-snippets akamud.vscode-theme-onedark alanz.vscode-hie-server CoenraadS.bracket-pair-colorizer dbaeumer.vscode-eslint DotJoshJohnson.xml eamodio.gitlens eg2.tslint eriklynd.json-tools fabianlauer.vs-code-xml-format humao.rest-client johnpapa.Angular2 justusadam.language-haskell minhthai.vscode-todo-parser ms-python.python ms-vsliveshare.vsliveshare naumovs.color-highlight npxms.hide-gitignored robinbentley.sass-indented wayou.vscode-todo-highlight wholroyd.jinja; do
		code --install-extension "$extension"
	done
else
	echo 'VS Code not found, not installing VS Code extensions.'
fi

